#!/bin/bash
#Minimal runscript for atmospheric dynamical cores
#--------------------------------------------------------------------------------------------------------
# define variables
cwd=`pwd`
platform=pgi                                    # A unique identifier for your platform
mpif=/usr/local/include
netcdf=/usr/local/include
#npes
template=$cwd/mkmf.template.$platform   # path to template for your platform
mkmf=$cwd/mkmf                      # path to executable mkmf
sourcedir=$cwd                           # path to directory containing model source code
mppnccombine=$cwd/mppnccombine.$platform # path to executable mppnccombine
mppnlib="-L/usr/local/lib"
mppnlibs="-lmpl -lmpich -lfmpich -lmpichf90 -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lm -lz"
#--------------------------------------------------------------------------------------------------------
execdir=$cwd/exec_axi      		 # where code is compiled and executable is created
pathnames=$cwd/path_names		 # path to file containing list of source paths
#--------------------------------------------------------------------------------------------------------
# create execdir
if [ ! -d ${execdir} ]
then
  mkdir ${execdir}
fi
#--------------------------------------------------------------------------------------------------------
# compile mppnccombine.c, will be used only if $npes > 1
if [ ! -f ${mppnccombine} ]
then
  pgcc -O -o $mppnccombine -I/usr/local/include -I$netcdf -I$mpif -L/usr/local/lib $cwd/postprocessing/mppnccombine.c $mppnlib $mppnlibs
  #gcc -O -o $mppnccombine -I/usr/local/include -L/usr/lib $cwd/../../postprocessing/mppnccombine.c -lnetcdf -lnetcdff
fi
#--------------------------------------------------------------------------------------------------------
# compile the model code and create executable
cd $execdir
perl $mkmf -p FMS.exe -t $template -c "-Duse_libMPI -Duse_netCDF" -a $sourcedir $pathnames /usr/local/include $sourcedir/shared/mpp/include $sourcedir/shared/include /usr/local/include $mpif $netcdf
make -f Makefile

